(()=>{const $=id=>document.getElementById(id),PATH='config/all/apis.txt';let file=null;
function repo(){return $('repo').value.trim().replace(/^https?:\/\/github\.com\//,'').replace(/\.git$/,'').replace(/\/$/,'')}
function token(){const t=$('token').value.trim();if(!t)throw Error('Enter a GitHub fine-grained token.');return t}
function auth(){return{Accept:'application/vnd.github+json',Authorization:'Bearer '+token(),'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'}}
async function gh(path,opt={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('https://api.github.com'+path,{...opt,signal:controller.signal,headers:{...auth(),...(opt.headers||{})}});const txt=await r.text();let d={};try{d=JSON.parse(txt)}catch{}if(!r.ok){const perms=r.headers.get('X-Accepted-GitHub-Permissions')||'';const detail=perms?' Required/accepted permission: '+perms+'.':'';const e=Error((d.message||'GitHub API error')+' (HTTP '+r.status+')'+detail);e.status=r.status;e.permissions=perms;throw e}return d}catch(e){if(e.name==='AbortError')throw Error('GitHub request timed out after 15 seconds. Check your internet connection and GitHub API access.');throw e}finally{clearTimeout(timer)}}
function msg(t,c='info'){ $('msg').textContent=t;$('msg').className='status '+c }
function apiMsg(t,c='info'){ $('apiConfigMsg').textContent=t;$('apiConfigMsg').className='status '+c }
function decode(c){return new TextDecoder().decode(Uint8Array.from(atob(c.replace(/\n/g,'')),x=>x.charCodeAt(0)))}
function parseRows(s){return s.split(/\n/).map((raw,i)=>{const line=raw.split('#',1)[0].trim();if(!line)return null;const p=line.split('|').map(x=>x.trim());if(p.length!==3)throw Error('Line '+(i+1)+': use API | environment | region');const [api,environment,region]=p;if(!api||!environment||!region)throw Error('Line '+(i+1)+': API, environment and region are required');if(!['west','westb','east','all','auto'].includes(region.toLowerCase()))throw Error('Line '+(i+1)+': region must be west, westb, east, all or auto');return{api,environment,region:region.toLowerCase()}}).filter(Boolean)}
async function load(){const d=await gh('/repos/'+repo()+'/contents/'+PATH+'?ref=main');file={...d,text:decode(d.content)};$('apiNames').value=file.text;render();return file.text}
function render(){let rows=[];try{rows=parseRows($('apiNames').value)}catch{return}const q=$('search').value.toLowerCase(),rf=$('inventoryRegion').value;const shown=rows.filter(x=>(rf==='all'||x.region==='all'||x.region==='auto'||x.region===rf)&&x.api.toLowerCase().includes(q));$('inventory').innerHTML=shown.map(x=>'<div class="api"><div><b>'+esc(x.api)+'</b><small>'+esc(x.environment)+' • '+esc(x.region.toUpperCase())+'</small></div><div class="apiActions"><button data-api="'+esc(x.api)+'" data-action="start">START</button><button class="danger" data-api="'+esc(x.api)+'" data-action="stop">STOP</button></div></div>').join('')||'<div class="muted">No APIs match the filter.</div>';document.querySelectorAll('#inventory [data-api]').forEach(b=>b.onclick=()=>dispatch(b.dataset.action,b.dataset.api))}
function esc(x){return x.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function parseSchedule(s){const bg=s.match(/business_group:\s*["']?([^\n"']+)/);if(bg)$('scheduleBg').value=bg[1].trim();const stop=s.match(/stop:\s*\n\s*enabled:\s*(true|false)\s*\n\s*time:\s*["']?(\d{2}:\d{2})/),start=s.match(/start:\s*\n\s*enabled:\s*(true|false)\s*\n\s*time:\s*["']?(\d{2}:\d{2})/);if(!/timezone:\s*Asia\/Kolkata/.test(s))throw Error('Only Asia/Kolkata is supported.');if(stop){$('stopEnabled').value=stop[1];$('stopTime').value=stop[2]}if(start){$('startEnabled').value=start[1];$('startTime').value=start[2]}}
function scheduleText(){const bg=$('scheduleBg').value.trim();if(!bg)throw Error('Business Group is required.');return '# Managed by MuleSoft Scheduler UI.\ntimezone: Asia/Kolkata\nbusiness_group: '+bg+'\n\nstop:\n  enabled: '+$('stopEnabled').value+'\n  time: "'+$('stopTime').value+'"\n\nstart:\n  enabled: '+$('startEnabled').value+'\n  time: "'+$('startTime').value+'"\n'}
async function connect(){try{msg('Connecting to GitHub…');const r=repo();if(!/^[-\\w.]+\\/[-\\w.]+$/.test(r))throw Error('Repository must be owner/name.');await gh('/repos/'+r);msg('Repository found. Loading scheduler configuration…');const sd=await gh('/repos/'+r+'/contents/config/schedules.yml?ref=main');parseSchedule(decode(sd.content));await load();$('controlBg').value=$('scheduleBg').value;await runStatus();await refreshDashboard();msg('Connected successfully.','ok')}catch(e){msg(e.status===401?'Invalid or expired GitHub token.':e.status===403?'GitHub denied this token. Grant the token access to this repository with Contents and Actions permissions.':e.message,'err')}}
async function save(){try{const bg=$('scheduleBg').value.trim();if(!bg)throw Error('Business Group is required.');const stopTime=$('stopTime').value,startTime=$('startTime').value;if(!stopTime||!startTime)throw Error('Stop and Start times are required.');msg('Queueing schedule update…');const base='/repos/'+repo();const payload={action:'save_schedule',business_group:bg,stop_time:stopTime,stop_enabled:$('stopEnabled').value,start_time:startTime,start_enabled:$('startEnabled').value};try{await gh(base+'/actions/workflows/mule-api-scheduler.yml/dispatches',{method:'POST',body:JSON.stringify({ref:'main',inputs:payload})});msg('Schedule update queued successfully.','ok')}catch(e){if(e.status!==403)throw e;await gh(base+'/dispatches',{method:'POST',body:JSON.stringify({event_type:'mule-api-scheduler',client_payload:payload})});msg('Schedule update queued through repository dispatch.','ok')}setTimeout(runStatus,2000)}catch(e){msg(e.message,'err')}}
async function saveApis(){try{const rows=parseRows($('apiNames').value);if(!rows.length)throw Error('Enter at least one API.');const clean=rows.map(x=>x.api+' | '+x.environment+' | '+x.region).join('\n')+'\n';const current=file||await load();await gh('/repos/'+repo()+'/contents/'+PATH,{method:'PUT',body:JSON.stringify({message:'ui: update master API inventory',content:btoa(unescape(encodeURIComponent(clean))),sha:current.sha,branch:'main'})});file={...current,text:clean};$('apiNames').value=clean;apiMsg('Saved '+rows.length+' API mapping(s). GitHub Actions will queue because config/all changed.','ok');render();setTimeout(runStatus,2000)}catch(e){apiMsg(e.message,'err')}}
async function upload(){const f=$('apiFile');if(!f.files?.length){f.click();return}$('apiNames').value=await f.files[0].text();await saveApis();f.value=''}
async function dispatch(action,api=""){try{const bg=($('controlBg').value||$('scheduleBg').value).trim();if(!bg)throw Error('Business Group is required.');const region=$('controlRegion').value;if(!confirm(action.toUpperCase()+' '+(api||'all APIs')+' in '+region.toUpperCase()+' for '+bg+'?'))return;msg('Dispatching '+action+'…');const base='/repos/'+repo();const payload={action,region,business_group:bg,api};try{await gh(base+'/actions/workflows/mule-api-scheduler.yml/dispatches',{method:'POST',body:JSON.stringify({ref:'main',inputs:payload})});msg((api?api+' ':'All APIs ')+action.toUpperCase()+' dispatched.','ok')}catch(primary){if(primary.status!==403)throw primary;msg('Workflow dispatch permission was denied; trying repository dispatch with Contents: write…');await gh(base+'/dispatches',{method:'POST',body:JSON.stringify({event_type:'mule-api-scheduler',client_payload:payload})});msg((api?api+' ':'All APIs ')+action.toUpperCase()+' dispatched through repository fallback.','ok')}setTimeout(runStatus,1500)}catch(e){msg(e.message,'err')}}
async function runStatus(){try{const d=await gh('/repos/'+repo()+'/actions/workflows/mule-api-scheduler.yml/runs?per_page=1'),r=d.workflow_runs?.[0];if(!r){$('run').textContent='No scheduler runs found.';return}$('run').innerHTML='<strong>'+esc(r.name||'MuleSoft API Scheduler')+'</strong><br>Status: <b>'+esc(r.status)+'</b> • Conclusion: <b>'+esc(r.conclusion||'running')+'</b><br>Run #'+r.run_number+' • '+new Date(r.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST<br><a href="'+esc(r.html_url)+'" target="_blank" rel="noreferrer">Open GitHub Actions run ↗</a>'}catch(e){$('run').textContent=e.message}}
async function refreshDashboard(){try{
 const inv=parseRows($('apiNames').value||''); $('dashTotal').textContent=inv.length;
 const env={};inv.forEach(x=>{const k=x.environment;env[k]=(env[k]||0)+1});
 $('envBreakdown').innerHTML=Object.entries(env).map(([k,v])=>'<div class="envRow"><div><b>'+esc(k)+'</b><small>'+v+' API'+(v===1?'':'s')+'</small></div><div class="envBar"><i style="width:'+Math.max(8,Math.round(v/Math.max(inv.length,1)*100))+'%"></i></div></div>').join('')||'<div class="muted">No APIs configured.</div>';
 const d=await gh('/repos/'+repo()+'/actions/workflows/mule-api-scheduler.yml/runs?per_page=8');
 const runs=d.workflow_runs||[]; const latest=runs[0];
 if(!latest){$('dashLatest').textContent='—';$('dashLatestMeta').textContent='No runs found';$('runHistory').innerHTML='<div class="muted">No scheduler executions found.</div>';return}
 $('dashLatest').textContent=(latest.name||'').includes('STOP')?'STOP':(latest.name||'').includes('START')?'START':'RUN';
 $('dashLatestMeta').textContent='Run #'+latest.run_number+' • '+esc(latest.conclusion||latest.status);
 $('dashSuccess').textContent=latest.conclusion==='success'?'✓':'—';$('dashFailed').textContent=latest.conclusion==='failure'?'1':'0';$('dashSkipped').textContent='—';
 $('runHistory').innerHTML=runs.map(x=>{const n=x.name||'MuleSoft API Scheduler';const action=n.match(/\b(START|STOP)\b/i)?.[1]?.toUpperCase()||'RUN';const state=x.status==='completed'?(x.conclusion||'unknown'):x.status;const cls=state==='success'?'good':state==='failure'?'bad':state==='in_progress'?'live':'neutral';return '<a class="historyRow" href="'+esc(x.html_url)+'" target="_blank" rel="noreferrer"><div class="runBadge '+cls+'">'+esc(action)+'</div><div class="historyMain"><b>#'+x.run_number+' — '+esc(n)+'</b><small>'+new Date(x.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST</small></div><span class="historyState '+cls+'">'+esc(state)+'</span></a>'}).join('');
}catch(e){$('runHistory').innerHTML='<div class="status err">'+esc(e.message)+'</div>'}}\n$('connect').onclick=connect;$('save').onclick=save;$('refresh').onclick=connect;$('saveApis').onclick=saveApis;$('uploadApis').onclick=upload;$('apiFile').onchange=upload;$('refreshRun').onclick=runStatus;$('refreshDashboard').onclick=refreshDashboard;$('search').oninput=render;$('inventoryRegion').onchange=render;$('controlBg').oninput=()=>{};$('startScope').onclick=()=>dispatch('start');$('stopScope').onclick=()=>dispatch('stop');$('apiNames').oninput=render;load().then(()=>refreshDashboard()).catch(()=>{});})();
