const KEY="mule-scheduler-draft-v2";
const groups=["eapi","papi","sapi"];
const regions=["all","west","westb","east"];
const $=id=>document.getElementById(id);
const blank=()=>({group:"eapi",region:"all",apps:""});
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{environment:"prod",stop:"06:00",start:"18:00",lists:[blank()]};

function save(){
  localStorage.setItem(KEY,JSON.stringify(state));
  showMessage("Saved on this device • "+new Date().toLocaleTimeString(),false);
}
function showMessage(message,error=false){
  $("message").textContent=message;
  $("message").style.background=error?"#fef2f2":"#ecfdf5";
  $("message").style.color=error?"#991b1b":"#166534";
}
function render(){
  $("environment").value=state.environment;
  $("stopTime").value=state.stop;
  $("startTime").value=state.start;
  $("lists").innerHTML="";
  state.lists.forEach((x,i)=>{
    const row=document.createElement("div");
    row.className="api-row";
    row.innerHTML=`
      <div class="api-head">
        <label>API type<select data-i="${i}" data-k="group">${groups.map(g=>`<option value="${g}">${g.toUpperCase()}</option>`).join("")}</select></label>
        <label>Region<select data-i="${i}" data-k="region">${regions.map(g=>`<option value="${g}">${g==="all"?"ALL REGIONS":g.toUpperCase()}</option>`).join("")}</select></label>
        <button class="remove" data-remove="${i}">Remove</button>
      </div>
      <label style="margin-top:12px">Applications
        <textarea data-i="${i}" data-k="apps" placeholder="app-one,app-two\nor one application per line">${x.apps}</textarea>
      </label>
      <small>Output: config/${x.group}/${x.region}/apis.txt</small>`;
    $("lists").appendChild(row);
    row.querySelector('[data-k="group"]').value=x.group;
    row.querySelector('[data-k="region"]').value=x.region;
  });
  document.querySelectorAll("[data-i]").forEach(el=>el.oninput=()=>{
    state.lists[+el.dataset.i][el.dataset.k]=el.value;
    save();
  });
  document.querySelectorAll("[data-remove]").forEach(el=>el.onclick=()=>{
    state.lists.splice(+el.dataset.remove,1);
    if(!state.lists.length)state.lists.push(blank());
    save();render();
  });
}
function names(t){
  return [...new Set(t.split(/[,\n]/).map(x=>x.trim()).filter(x=>x&&!x.startsWith("#")))];
}
function validate(){
  const errors=[];
  if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(state.stop))errors.push("Invalid stop time");
  if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(state.start))errors.push("Invalid start time");
  state.lists.forEach((x,i)=>{
    if(!groups.includes(x.group)||!regions.includes(x.region))errors.push("Invalid type/region on row "+(i+1));
    if(!names(x.apps).length)errors.push("Row "+(i+1)+" has no applications");
  });
  showMessage(errors.length?errors.join(" • "):"Configuration is valid.",errors.length>0);
  return !errors.length;
}
function download(path,content){
  const a=document.createElement("a");
  a.href=URL.createObjectURL(new Blob([content],{type:"text/plain"}));
  a.download=path.replaceAll("/","__");
  a.click();
  setTimeout(()=>URL.revokeObjectURL(a.href),500);
}
function exportConfig(){
  if(!validate())return;
  const files=[];
  for(const group of groups){
    for(const region of regions){
      const note=region==="all"?"# Applications in this file are controlled in West + WestB + East.\n":"# Applications in this file are controlled only in the "+region.toUpperCase()+" region.\n";
      files.push({path:"config/"+group+"/"+region+"/apis.txt",content:"# Generated by MuleSoft Scheduler Console\n"+note});
    }
  }
  const map=new Map(files.map(f=>[f.path,f]));
  state.lists.forEach(x=>{
    const targetRegions=x.region==="all"?["all"]:[x.region];
    targetRegions.forEach(region=>{
      const file=map.get("config/"+x.group+"/"+region+"/apis.txt");
      names(x.apps).forEach(app=>{file.content+=app+"\n";});
    });
  });
  files.push({path:"config/schedules.yml",content:"# Generated by MuleSoft Scheduler Console\ntimezone: Asia/Kolkata\n\nstop:\n  enabled: true\n  time: \""+state.stop+"\"\n\nstart:\n  enabled: true\n  time: \""+state.start+"\"\n"});
  $("preview").textContent=files.map(f=>"--- "+f.path+" ---\n"+f.content).join("\n");
  files.forEach(f=>download(f.path,f.content));
  showMessage("Exported 12 API files (3 groups × 4 folders) plus schedules.yml.",false);
}
$("environment").onchange=e=>{state.environment=e.target.value;save()};
$("stopTime").onchange=e=>{state.stop=e.target.value;save()};
$("startTime").onchange=e=>{state.start=e.target.value;save()};
$("save").onclick=save;
$("add").onclick=()=>{state.lists.push(blank());save();render()};
$("validate").onclick=validate;
$("export").onclick=exportConfig;
$("reset").onclick=()=>{localStorage.removeItem(KEY);location.reload()};
render();
